augmentations: null
balance: false
batch_level_subsampling: false
batch_norm: true
batch_size: 16
class_names:
- noise
- powlfemale
class_types:
- segment
- segment
class_weights: null
data_dir: E:/adultmodel4/training data.npy
data_folder: E:/adultmodel4/training data
data_hash: 446964d77d637044f897ac1e12cd1600
data_padding: 128
data_splits:
  test: 0.2
  train: 0.6
  val: 0.2
delete_intermediate_store: true
dilations:
- 1
- 2
- 4
- 8
- 16
event_std_seconds: 0.0016
file_split_dict: {}
file_splits: {}
filename_endsample_test: []
filename_endsample_train: []
filename_endsample_val: []
filename_startsample_test: []
filename_startsample_train: []
filename_startsample_val: []
filename_test: []
filename_train: []
filename_val: []
fill_gaps_max: null
fill_gaps_min: null
fill_gaps_steps: null
first_sample_train: 0
first_sample_val: 0
fraction_data: null
gap_seconds: 0.0
ignore_boundaries: true
kernel_size: 32
last_sample_train: null
last_sample_val: null
learning_rate: 0.001
log_messages: true
make_single_class_datasets: false
min_len_max: null
min_len_min: null
min_len_steps: null
model_name: tcn_stft
nb_channels: 1
nb_classes: 2
nb_conv: 4
nb_epoch: 100
nb_filters: 32
nb_freq: 1
nb_hist: 2048
nb_lstm_units: 0
nb_pre_conv: 4
nb_stacks: 2
output_stride: 1
post_opt: false
pre_kernel_size: 3
pre_nb_conv: '16'
pre_nb_dft: 32
pre_nb_filters: 16
reduce_lr: true
reduce_lr_patience: 5
return_sequences: true
sample_weight_mode: temporal
samplerate_x_Hz: 48000.0
samplerate_y_Hz: 48000.0
save_dir: E:/adultmodel4/trainingdata2.res
save_name: null
save_prefix: ''
seed: null
split_in_two: true
store_folder: E:/adultmodel4/training data.npy
stride: 1792
tensorboard: false
upsample: true
use_separable:
- false
- false
- false
- false
verbose: 2
version_data: true
wandb_api_token: null
wandb_entity: null
wandb_project: null
with_y_hist: true
x_suffix: ''
y_offset: 0
y_suffix: ''
